### ISSUE TITLE
no_std support?

### ISSUE THREAD

**Issue by SamiPerttu** [novacrazy/numeric-array#7]
Hi! Thank you for this amazing crate, it's been very useful in [FunDSP](https://github.com/SamiPerttu/fundsp).

My issue is that it appears the `num-traits` crate is being brought in with the `std` feature enabled and this is causing problems in embedded use. Would it be possible to disable the `std` feature in `num-traits`?

**Comment by novacrazy** [comment]
I'll try to release a version soon with this and some more optimizations/fixes. I also just released `generic-array` 1.0.1 which should improve performance in `numeric-array` significantly.

**Comment by SamiPerttu** [comment]
Solved in version 0.6.1.
